  - name: Execute API Call GET For "{{item.split(':',1)[0]}}"
    uri:
      url: "http://localhost:8080/public/v1/config/{{item.split(':',1)[0]}}"
      method: GET
      body: "{{ item.split(':',1)[1] }}"
      body_format: json
      return_content: yes
      status_code: 200,404
    register: result
  
  - name: Execute API Call POST For "{{item.split(':',1)[0]}}"
    uri:
      url: "http://localhost:8080/public/v1/config/{{item.split(':',1)[0]}}"
      method: POST
      body: "{{ item.split(':',1)[1] }}"
      body_format: json
      status_code: 201
      return_content: yes
    when: result.status == 404
    ignore_errors: yes
    register: post_result
    failed_when:
      - "post_result.status != 201"
    changed_when: "post_result.status == 201"

  - name: Execute API Call PATCH For "{{item.split(':',1)[0]}}"
    uri:
      url: "http://localhost:8080/public/v1/config/{{item.split(':',1)[0]}}"
      method: PATCH
      body: "{{ item.split(':',1)[1] }}"
      body_format: json
      status_code: 200
      return_content: yes
    when: result.status == 200
    ignore_errors: yes
    register: patch_result
    failed_when: 
      - "'Error: Nothing to be updated.' not in patch_result.json.Result"
      - "patch_result.status != 200"
    changed_when: "patch_result.status == 200"
